# drupal_core_path: /var/www/drupal-7.x-dev
# modules_dir: "{{ drupal_core_path }}/sites/all/modules"
# themes_dir: "{{ drupal_core_path  }}/sites/all/themes"
# libraries_dir: "{{ drupal_core_path }}/sites/all/libraries"

modules:
  - features
  - libraries
  - strongarm
  - views
  - zen
  - feeds
  - feeds_tamper
  - references
  - entityreference
  - media
  - file_entity
  - wysiwyg_mediaembed
  - pathauto
  - special_menu_items
  - responsive_menus
  - superfish
  - image_resize_filter
  - professional_theme
  - skeletontheme
  - multipurpose
  - impact_theme
  - module_filter
  
submodules:
 - views_ui
 - skeletiontheme
 - feeds_ui
 - feeds_import
 - feeds_tamper
 - feeds_tamper_ui
 - node_reference
 - entity-reference
 - image_resize_filter
 - media
 - mediafield
 - module_filter
 - pathauto
 - responsive_menus
 - special_menu_items
 - wysiwyg_mediaembed
 
 - 
 

